# Generated by Django 4.1.6 on 2023-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appThree", "0002_rename_user_userinfo_userprofileinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pic"),
        ),
    ]
